test_strlist: strlist.c test_strlist.c
	clang -Wall -g -o test_strlist strlist.c test_strlist.c
wordle: strlist.c wordle.c
	clang -Wall -g -o wordle strlist.c wordle.c
clean:
	rm -f test_strlist wordle *.o *~
